name: "coverage"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ArtiomTr/jest-coverage-report-action@cab9a826443a9e21de232191d22d372cb2a3381c
